/**
 * Vector backend. Layout + draw list -> a single SVG string.
 *
 * Determinism rules enforced here:
 *  - no timestamps, no random ids, no Math.random
 *  - every number is printed through `n()` so output is byte-stable
 *  - defs ids are derived from a counter in first-use order
 */

import { FONT_STACKS } from '../vocabulary.js';
import { hexToRgb } from '../validate.js';
import { canonicalJSON } from '../hash.js';

/**
 * @param {object} layout
 * @param {{ pretty?:boolean }} [options]
 * @returns {string}
 */
export function renderSvg(layout, options = {}) {
  const pretty = options.pretty !== false;
  const nl = pretty ? '\n' : '';
  const pad = pretty ? '  ' : '';

  const defs = new Defs();
  const body = [];

  if (layout.background) body.push(...backgroundRect(layout, defs));

  for (const node of layout.nodes) {
    if (node.type === 'group') body.push(...groupOp(node, defs));
    else if (node.type === 'panel') body.push(...panelOp(node, defs));
    else if (node.type === 'image') body.push(...placeholderOp(node, defs));
    else if (node.type === 'text') body.push(...textOp(node, defs));
    else if (node.type === 'icon') body.push(...iconOp(node, defs));
  }

  const title = escapeXml(layout.name ?? 'WritterArt');
  const defsMarkup = defs.render(pretty);

  return (
    `<svg xmlns="http://www.w3.org/2000/svg" width="${n(layout.width)}" height="${n(layout.height)}" ` +
    `viewBox="0 0 ${n(layout.width)} ${n(layout.height)}" role="img" aria-label="${title}">${nl}` +
    `${pad}<title>${title}</title>${nl}` +
    `${pad}<desc>Generated by WritterArt from a declarative scene description. Deterministic: same source, same pixels.</desc>${nl}` +
    (defsMarkup ? `${defsMarkup}${nl}` : '') +
    body.map((line) => (pretty ? `${pad}${line}` : line)).join(nl) +
    (body.length ? nl : '') +
    `</svg>` + (pretty ? '\n' : '')
  );
}

// ------------------------------------------------------------------ defs

class Defs {
  constructor() {
    this.entries = [];
    this.index = new Map();
    this.shadows = new Map();
  }

  paintKey(paint) {
    return canonicalJSON(paint);
  }

  paint(paint) {
    if (!paint || paint.kind === 'none') return 'none';
    const key = this.paintKey(paint);
    if (this.index.has(key)) return `url(#${this.index.get(key)})`;

    const id = `wrt-p${this.index.size}`;
    this.index.set(key, id);

    if (paint.kind === 'color') {
      this.entries.push(`<linearGradient id="${id}" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${paint.color}" stop-opacity="${n(paint.opacity ?? 1)}"/></linearGradient>`);
      return `url(#${id})`;
    }

    if (paint.kind === 'material') {
      const angle = ((paint.angle ?? 90) - 90) * (Math.PI / 180);
      const x1 = 0.5 - Math.cos(angle) / 2;
      const y1 = 0.5 - Math.sin(angle) / 2;
      const x2 = 0.5 + Math.cos(angle) / 2;
      const y2 = 0.5 + Math.sin(angle) / 2;
      return this.gradient(id, x1, y1, x2, y2, paint.stops);
    }

    if (paint.kind === 'linear') {
      const angle = ((paint.angle ?? 90) - 90) * (Math.PI / 180);
      const x1 = 0.5 - Math.cos(angle) / 2;
      const y1 = 0.5 - Math.sin(angle) / 2;
      const x2 = 0.5 + Math.cos(angle) / 2;
      const y2 = 0.5 + Math.sin(angle) / 2;
      return this.gradient(id, x1, y1, x2, y2, paint.stops);
    }

    if (paint.kind === 'radial') {
      const { cx = 0.5, cy = 0.5, r = 0.75, stops = [] } = paint;
      this.entries.push(
        `<radialGradient id="${id}" cx="${n(cx)}" cy="${n(cy)}" r="${n(r)}">${stops
          .map((stop) => `<stop offset="${n(stop.offset)}" stop-color="${stop.color}"/>`)
          .join('')}</radialGradient>`
      );
      return `url(#${id})`;
    }

    if (paint.kind === 'pattern') {
      const size = Math.max(2, paint.size ?? 24);
      const fg = paint.fg ?? '#ffffff';
      const bg = paint.bg ?? 'none';
      const opacity = paint.opacity ?? 1;
      const width = paint.width ?? 1;
      const body = patternBody(paint.pattern, size, fg, width);
      this.entries.push(
        `<pattern id="${id}" width="${n(size)}" height="${n(size)}" patternUnits="userSpaceOnUse">` +
        (bg && bg !== 'none' ? `<rect width="${n(size)}" height="${n(size)}" fill="${bg}"/>` : '') +
        `<g opacity="${n(opacity)}">${body}</g></pattern>`
      );
      return `url(#${id})`;
    }

    return 'none';
  }

  gradient(id, x1, y1, x2, y2, stops = []) {
    this.entries.push(
      `<linearGradient id="${id}" x1="${n(round4(x1))}" y1="${n(round4(y1))}" x2="${n(round4(x2))}" y2="${n(round4(y2))}">${stops
        .map((stop) => `<stop offset="${n(stop.offset)}" stop-color="${stop.color}"/>`)
        .join('')}</linearGradient>`
    );
    return `url(#${id})`;
  }

  shadow(shadow) {
    if (!shadow) return '';
    const key = canonicalJSON(shadow);
    if (this.shadows.has(key)) return this.shadows.get(key);
    const id = `wrt-f${this.shadows.size}`;
    const { color, opacity } = splitAlpha(shadow.color);
    const std = Math.max(0, shadow.blur / 2);
    this.entries.push(
      `<filter id="${id}" x="-50%" y="-50%" width="200%" height="200%" color-interpolation-filters="sRGB">` +
      `<feDropShadow dx="${n(shadow.dx)}" dy="${n(shadow.dy)}" stdDeviation="${n(round4(std))}" flood-color="${color}" flood-opacity="${n(opacity)}"/>` +
      `</filter>`
    );
    this.shadows.set(key, id);
    return `url(#${id})`;
  }

  render(pretty) {
    if (!this.entries.length) return '';
    const nl = pretty ? '\n' : '';
    const pad = pretty ? '    ' : '';
    return `<defs>${nl}${this.entries.map((entry) => `${pad}${entry}`).join(nl)}${nl}  </defs>`;
  }
}

function patternBody(pattern, size, fg, width) {
  switch (pattern) {
    case 'malla':
      return `<path d="M ${n(size)} 0 L 0 0 L 0 ${n(size)}" fill="none" stroke="${fg}" stroke-width="${n(width)}"/>`;
    case 'puntos':
      return `<circle cx="${n(size / 2)}" cy="${n(size / 2)}" r="${n(Math.max(1, size / 10))}" fill="${fg}"/>`;
    case 'rayas':
      return `<path d="M ${n(-size)} ${n(size)} L ${n(size)} ${n(-size)} M 0 ${n(size * 2)} L ${n(size * 2)} 0" fill="none" stroke="${fg}" stroke-width="${n(width)}"/>`;
    case 'ondas':
      return `<path d="M 0 ${n(size / 2)} Q ${n(size / 4)} 0 ${n(size / 2)} ${n(size / 2)} T ${n(size)} ${n(size / 2)}" fill="none" stroke="${fg}" stroke-width="${n(width)}"/>`;
    default:
      return `<rect width="${n(size)}" height="${n(size)}" fill="${fg}"/>`;
  }
}

// ------------------------------------------------------------------ ops

function backgroundRect(layout, defs) {
  const paint = defs.paint(layout.background);
  return [
    `<rect id="wrt-bg" x="0" y="0" width="${n(layout.width)}" height="${n(layout.height)}" fill="${paint}"/>`
  ];
}

/** A group is only painted when it actually has a surface, but it may have one. */
function groupOp(node, defs) {
  const style = node.style ?? {};
  if (!style.fill && !style.stroke && !style.shadow) return [];
  return panelOp(node, defs);
}

function panelOp(node, defs) {
  const style = node.style ?? {};
  const out = [];
  const fill = defs.paint(style.fill);
  const filter = defs.shadow(style.shadow);
  const attrs = [
    `id="${escapeXml(node.id)}"`,
    `x="${n(node.box.x)}"`,
    `y="${n(node.box.y)}"`,
    `width="${n(node.box.w)}"`,
    `height="${n(node.box.h)}"`,
    `rx="${n(style.radius ?? 0)}"`,
    `fill="${fill}"`
  ];
  if (style.stroke) attrs.push(`stroke="${style.stroke.color}"`, `stroke-width="${n(style.stroke.width)}"`);
  if (style.opacity !== undefined && style.opacity !== 1) attrs.push(`opacity="${n(style.opacity)}"`);
  if (filter) attrs.push(`filter="${filter}"`);
  out.push(`<rect ${attrs.join(' ')}/>`);
  return out;
}

function placeholderOp(node, defs) {
  const style = node.style ?? {};
  const fill = defs.paint(style.fill);
  const filter = defs.shadow(style.shadow);
  const dash = style.stroke?.dash?.length ? ` stroke-dasharray="${style.stroke.dash.map((d) => n(d)).join(' ')}"` : '';
  const attrs = [
    `id="${escapeXml(node.id)}"`,
    `x="${n(node.box.x)}"`,
    `y="${n(node.box.y)}"`,
    `width="${n(node.box.w)}"`,
    `height="${n(node.box.h)}"`,
    `rx="${n(style.radius ?? 0)}"`,
    `fill="${fill}"`
  ];
  if (style.stroke) attrs.push(`stroke="${style.stroke.color}"`, `stroke-width="${n(style.stroke.width)}"`, dash.trim());
  if (filter) attrs.push(`filter="${filter}"`);
  return [`<rect ${attrs.join(' ')}/>`];
}

function textOp(node, defs) {
  void defs;
  const style = node.text;
  const family = FONT_STACKS[style.family] ?? FONT_STACKS.sans;
  const out = [];
  const prefix = style.prefix ? 1 : 0;

  style.lines.forEach((line, index) => {
    const isPrefix = prefix && index === 0;
    const size = isPrefix ? style.size * 0.72 : style.size;
    const baseline = style.size * 0.8 + (isPrefix ? 0 : style.size * 1.05 + (index - 1) * style.size * style.lineHeight);
    const anchor = style.align === 'center' ? 'middle' : style.align === 'right' ? 'end' : 'start';
    const x = style.align === 'center' ? node.box.x + node.box.w / 2 : style.align === 'right' ? node.box.x + node.box.w : node.box.x;
    const content = isPrefix ? String(style.prefix).toUpperCase() : style.uppercase ? String(line).toUpperCase() : line;
    if (!content) return;
    const attrs = [
      `x="${n(round4(x))}"`,
      `y="${n(round4(node.box.y + baseline))}"`,
      `font-family="${escapeXml(family)}"`,
      `font-size="${n(round4(size))}"`,
      `font-weight="${isPrefix ? 600 : style.weight}"`,
      `fill="${escapeXml(style.color ?? '#111418')}"`
    ];
    if (anchor !== 'start') attrs.push(`text-anchor="${anchor}"`);
    if (style.tracking) attrs.push(`letter-spacing="${n(round4(style.tracking * size))}"`);
    out.push(`<text ${attrs.join(' ')}>${escapeXml(content)}</text>`);
  });

  if (style.opacity !== undefined && style.opacity !== 1 && out.length) {
    return [`<g opacity="${n(style.opacity)}">`, ...out.map((line) => `  ${line}`), `</g>`];
  }
  return out;
}

function iconOp(node, defs) {
  void defs;
  const spec = node.icon;
  if (!spec) return [];
  const scale = spec.size / 24;
  const attrs = [
    `id="${escapeXml(node.id)}"`,
    `transform="translate(${n(round4(node.box.x))} ${n(round4(node.box.y))}) scale(${n(round4(scale))})"`,
    `fill="none"`,
    `stroke="${escapeXml(spec.color ?? '#111418')}"`,
    `stroke-width="${n(round4(2 / scale))}"`,
    `stroke-linecap="round"`,
    `stroke-linejoin="round"`
  ];
  if (spec.opacity !== undefined && spec.opacity !== 1) attrs.push(`opacity="${n(spec.opacity)}"`);
  return [`<g ${attrs.join(' ')}><path d="${spec.path}"/></g>`];
}

// ------------------------------------------------------------------ helpers

function splitAlpha(color) {
  const { r, g, b, a } = hexToRgb(color);
  return {
    color: `#${[r, g, b].map((v) => v.toString(16).padStart(2, '0')).join('')}`,
    opacity: a
  };
}

function round4(value) {
  return Math.round(value * 10000) / 10000;
}

/** Stable number formatting: no locale, no -0, no float noise. */
export function n(value) {
  if (!Number.isFinite(value)) return '0';
  const rounded = Math.round(value * 100) / 100;
  return Object.is(rounded, -0) ? '0' : String(rounded);
}

export function escapeXml(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}