import { useEffect, useMemo, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useLanguage } from '../../context/LanguageContext';
import { ROUTES } from '../../config/constants';
import { sendToAI, getActiveTextModel } from '../../services/ai';
import { ARTIFACT_TYPES, deleteArtifact, getArtifact, listArtifacts, saveArtifact, snapshotArtifact, undoArtifact, redoArtifact } from '../../services/artifacts/artifactEngine';
import { addDiagramConnector, addDiagramNode, autoLayoutDiagram, createDiagramArtifact, diagramToSvg, parseDiagramDsl, removeDiagramNode, updateDiagramNode } from '../../services/artifacts/diagramEngine';
import { addBlockToPage, addDocumentPage, addPdfAnnotation, createDocumentArtifact, createPdfArtifact, createTextBlock, documentFromText, downloadPdfBlob, removeDocumentPage, removePdfAnnotation, serializeDocumentToPdf, updateBlock } from '../../services/artifacts/pdfEngine';
import { applyAiArtifactOperations, planArtifactOperations } from '../../services/artifacts/aiArtifactOps';
import './ArtifactStudio.css';

const TYPES = [ARTIFACT_TYPES.DIAGRAM, ARTIFACT_TYPES.DOCUMENT, ARTIFACT_TYPES.PDF];
function downloadText(content, filename, type) { const blob = new Blob([content], { type }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = filename; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }

export default function ArtifactStudio() {
  const { t } = useLanguage(); const navigate = useNavigate(); const fileInput = useRef(null);
  const [items, setItems] = useState([]); const [active, setActive] = useState(null); const [selectedNode, setSelectedNode] = useState(null); const [selectedPageId, setSelectedPageId] = useState(null); const [dsl, setDsl] = useState(''); const [prompt, setPrompt] = useState(''); const [pending, setPending] = useState([]); const [status, setStatus] = useState(''); const [busy, setBusy] = useState(false); const [drag, setDrag] = useState(null);
  const refresh = async (id = active?.id) => { const list = await listArtifacts(); setItems(list); const current = id ? await getArtifact(id) : list[0]; setActive(current || null); };
  useEffect(() => { refresh(); }, []);
  const persist = async (value, message = '') => { const saved = await saveArtifact(value); setActive(saved); await refresh(saved.id); if (message) setStatus(message); return saved; };
  const page = useMemo(() => active?.content?.pages?.find((p) => p.id === selectedPageId) || active?.content?.pages?.[0] || null, [active, selectedPageId]);
  const node = useMemo(() => active?.content?.elements?.find((n) => n.id === selectedNode) || null, [active, selectedNode]);

  const createNew = async (type) => { const value = type === ARTIFACT_TYPES.DIAGRAM ? createDiagramArtifact({ name: t('artifactStudio.defaults.diagram') }) : type === ARTIFACT_TYPES.PDF ? createPdfArtifact({ name: t('artifactStudio.defaults.pdf') }) : createDocumentArtifact({ name: t('artifactStudio.defaults.document') }); await persist(value, t('artifactStudio.status.created')); };
  const importPdf = async (file) => { if (!file || file.type !== 'application/pdf') return setStatus(t('artifactStudio.status.invalidPdf')); if (file.size > 100 * 1024 * 1024) return setStatus(t('artifactStudio.status.pdfTooLarge')); const dataUrl = await new Promise((resolve, reject) => { const r = new FileReader(); r.onload = () => resolve(r.result); r.onerror = () => reject(r.error); r.readAsDataURL(file); }); await persist(createPdfArtifact({ name: file.name, sourceDataUrl: dataUrl }), t('artifactStudio.status.imported')); };
  const exportActive = () => { if (!active) return; if (active.type === ARTIFACT_TYPES.DIAGRAM) return downloadText(diagramToSvg(active), `${active.name}.svg`, 'image/svg+xml'); if (active.type === ARTIFACT_TYPES.DOCUMENT) return downloadPdfBlob(serializeDocumentToPdf(active), active.name); if (active.content?.originalDataUrl) { const a = document.createElement('a'); a.href = active.content.originalDataUrl; a.download = active.name; a.click(); } };
  const runAi = async () => { if (!active || !prompt.trim()) return; setBusy(true); setStatus(t('artifactStudio.status.aiWorking')); try { if (active.type === ARTIFACT_TYPES.DOCUMENT) { const model = getActiveTextModel(); if (!model) throw new Error(t('artifactStudio.status.noModel')); const result = await sendToAI(prompt, model, { temperature: 0.4 }); if (!result?.success) throw new Error(result?.error || t('artifactStudio.status.aiFailed')); const generated = documentFromText(result.content, { name: active.name, pageSize: active.content?.pageSize || 'a4' }); await persist(snapshotArtifact({ ...active, content: generated.content }, prompt), t('artifactStudio.status.aiApplied')); } else { const ops = await planArtifactOperations({ artifact: active, prompt, selection: selectedNode || selectedPageId || null }); setPending(ops); setStatus(t('artifactStudio.status.aiPreview', { count: ops.length })); } } catch (error) { setStatus(error?.message || t('artifactStudio.status.aiFailed')); } finally { setBusy(false); } };
  const applyAi = async () => { if (!pending.length) return; await persist(snapshotArtifact(applyAiArtifactOperations(active, pending), prompt), t('artifactStudio.status.aiApplied')); setPending([]); setPrompt(''); };
  const pointerDown = (event, n) => { setSelectedNode(n.id); setDrag({ id: n.id, px: event.clientX, py: event.clientY, x: n.x, y: n.y }); event.currentTarget.setPointerCapture?.(event.pointerId); };
  const pointerMove = (event) => { if (!drag || active?.type !== ARTIFACT_TYPES.DIAGRAM) return; setActive(updateDiagramNode(active, drag.id, { x: Math.round((drag.x + event.clientX - drag.px) / 10) * 10, y: Math.round((drag.y + event.clientY - drag.py) / 10) * 10 })); };
  const pointerUp = async () => { if (drag && active) await persist(active); setDrag(null); };

  return <div className="oc-artifact-studio">
    <header className="oc-artifact-header"><div><button className="oc-artifact-link" onClick={() => navigate(ROUTES.WORKSPACE)}>{t('artifactStudio.back')}</button><h1>{t('artifactStudio.title')}</h1><p>{t('artifactStudio.subtitle')}</p></div><div className="oc-artifact-header-actions">{TYPES.map((type) => <button key={type} onClick={() => createNew(type)}>{t(`artifactStudio.types.${type}`)}</button>)}<button onClick={() => fileInput.current?.click()}>{t('artifactStudio.importPdf')}</button><input ref={fileInput} hidden type="file" accept="application/pdf" onChange={(e) => importPdf(e.target.files?.[0])}/></div></header>
    <div className="oc-artifact-layout">
      <aside className="oc-artifact-sidebar"><strong>{t('artifactStudio.library')}</strong>{items.map((item) => <button key={item.id} className={`oc-artifact-item ${active?.id === item.id ? 'is-active' : ''}`} onClick={() => refresh(item.id)}><span>{item.name}</span><small>{t(`artifactStudio.types.${item.type}`)}</small></button>)}</aside>
      <main className="oc-artifact-main">{!active ? <div className="oc-artifact-empty"><h2>{t('artifactStudio.emptyTitle')}</h2><p>{t('artifactStudio.emptyDescription')}</p></div> : <><div className="oc-artifact-toolbar"><input value={active.name} aria-label={t('artifactStudio.name')} onChange={(e) => setActive({ ...active, name: e.target.value })} onBlur={() => persist(active)}/><button disabled={active.operationCursor < 0} onClick={() => persist(undoArtifact(active))}>{t('artifactStudio.undo')}</button><button disabled={active.operationCursor >= (active.operations?.length || 0) - 1} onClick={() => persist(redoArtifact(active))}>{t('artifactStudio.redo')}</button><button onClick={exportActive}>{t('artifactStudio.export')}</button><button onClick={async () => { await deleteArtifact(active.id); setActive(null); await refresh(null); }}>{t('artifactStudio.delete')}</button></div>
        {active.type === ARTIFACT_TYPES.DIAGRAM && <div className="oc-diagram-editor"><div className="oc-diagram-tools"><button onClick={() => persist(addDiagramNode(active, { label: `${t('artifactStudio.diagram.node')} ${(active.content?.elements?.length || 0) + 1}` }))}>{t('artifactStudio.diagram.addNode')}</button><button disabled={!selectedNode} onClick={() => { const target = active.content.elements.find((n) => n.id !== selectedNode); if (target) persist(addDiagramConnector(active, { from: selectedNode, to: target.id })); }}>{t('artifactStudio.diagram.connect')}</button><button onClick={() => persist(autoLayoutDiagram(active))}>{t('artifactStudio.diagram.layout')}</button><button disabled={!selectedNode} onClick={() => persist(removeDiagramNode(active, selectedNode))}>{t('artifactStudio.diagram.remove')}</button></div><svg className="oc-diagram-canvas" viewBox="0 0 1200 800" onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp}><defs><marker id="oc-editor-arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z"/></marker></defs>{(active.content?.connectors || []).map((edge) => { const a = active.content.elements.find((n) => n.id === edge.from), b = active.content.elements.find((n) => n.id === edge.to); return a && b ? <line key={edge.id} className="oc-diagram-edge" x1={a.x+a.width/2} y1={a.y+a.height/2} x2={b.x+b.width/2} y2={b.y+b.height/2} markerEnd="url(#oc-editor-arrow)"/> : null; })}{(active.content?.elements || []).map((n) => <g key={n.id} className={`oc-diagram-node ${selectedNode === n.id ? 'is-selected' : ''}`} onPointerDown={(e) => pointerDown(e,n)}><rect x={n.x} y={n.y} width={n.width} height={n.height} rx="16"/><text x={n.x+n.width/2} y={n.y+n.height/2+5} textAnchor="middle">{n.label}</text></g>)}</svg><div className="oc-diagram-dsl"><textarea value={dsl} onChange={(e) => setDsl(e.target.value)} placeholder={t('artifactStudio.diagram.dslPlaceholder')}/><button onClick={async () => { const generated = parseDiagramDsl(dsl); generated.id = active.id; generated.name = active.name; await persist(generated, t('artifactStudio.status.dslApplied')); }}>{t('artifactStudio.diagram.applyDsl')}</button></div></div>}
        {active.type === ARTIFACT_TYPES.DOCUMENT && <div className="oc-document-editor"><div className="oc-document-pages">{(active.content?.pages || []).map((p,i) => <button key={p.id} className={page?.id===p.id?'is-active':''} onClick={() => setSelectedPageId(p.id)}>{t('artifactStudio.document.page',{number:i+1})}</button>)}<button onClick={() => persist(addDocumentPage(active))}>{t('artifactStudio.document.addPage')}</button><button disabled={!page || active.content.pages.length <= 1} onClick={() => persist(removeDocumentPage(active,page.id))}>{t('artifactStudio.document.removePage')}</button></div><div className="oc-document-page">{(page?.blocks || []).map((block) => block.type === 'text' ? <textarea key={block.id} className="oc-document-block" value={block.text} onChange={(e) => setActive(updateBlock(active,page.id,block.id,{text:e.target.value}))} onBlur={() => persist(active)}/> : null)}<button onClick={() => persist(addBlockToPage(active,page.id,createTextBlock({text:t('artifactStudio.document.newText')}))}>{t('artifactStudio.document.addText')}</button></div></div>}
        {active.type === ARTIFACT_TYPES.PDF && <div className="oc-pdf-editor"><div className="oc-pdf-preview-wrap">{active.content?.originalDataUrl ? <iframe title={active.name} className="oc-pdf-preview" src={active.content.originalDataUrl}/> : <div className="oc-artifact-empty">{t('artifactStudio.pdf.noOriginal')}</div>}</div><aside className="oc-pdf-inspector"><h3>{t('artifactStudio.pdf.annotations')}</h3><button onClick={() => persist(addPdfAnnotation(active,{text:t('artifactStudio.pdf.newNote'),page:1}))}>{t('artifactStudio.pdf.addNote')}</button>{(active.content?.annotations || []).map((ann) => <div key={ann.id} className="oc-pdf-annotation"><textarea value={ann.text} onChange={(e) => setActive({...active,content:{...active.content,annotations:active.content.annotations.map((x)=>x.id===ann.id?{...x,text:e.target.value}:x)}})} onBlur={() => persist(active)}/><button onClick={() => persist(removePdfAnnotation(active,ann.id))}>{t('artifactStudio.remove')}</button></div>)}<p>{t('artifactStudio.pdf.nonDestructive')}</p></aside></div>}</>}</main>
      <aside className="oc-artifact-ai-panel"><h2>{t('artifactStudio.ai.title')}</h2>{node && <input value={node.label} onChange={(e)=>setActive(updateDiagramNode(active,node.id,{label:e.target.value}))} onBlur={()=>persist(active)}/>}<textarea value={prompt} onChange={(e)=>setPrompt(e.target.value)} placeholder={t('artifactStudio.ai.placeholder')}/><button disabled={busy || !prompt.trim()} onClick={runAi}>{busy?t('artifactStudio.ai.working'):t('artifactStudio.ai.plan')}</button>{pending.length>0&&<div className="oc-artifact-ai-preview"><pre>{JSON.stringify(pending,null,2)}</pre><button onClick={applyAi}>{t('artifactStudio.ai.apply')}</button><button onClick={()=>setPending([])}>{t('artifactStudio.ai.discard')}</button></div>}{status&&<p className="oc-artifact-status">{status}</p>}</aside>
    </div>
  </div>;
}
