import { ARTIFACT_TYPES, OPERATION_TYPES, applyArtifactOperation, createArtifact, withHistoryBase } from './artifactEngine.js';

export const DIAGRAM_SHAPES = Object.freeze(['rect', 'rounded', 'ellipse', 'diamond']);
export function createDiagramArtifact({ name = 'Untitled diagram', projectId = null, prompt = null } = {}) { return withHistoryBase(createArtifact({ type: ARTIFACT_TYPES.DIAGRAM, name, projectId, prompt, content: { width: 1200, height: 800, elements: [], connectors: [], viewport: { x: 0, y: 0, zoom: 1 } }, metadata: { format: 'oc-diagram/1', grid: 20, snap: true } })); }
export function createDiagramNode(input = {}) { return { id: input.id || `node_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`, kind: 'node', shape: DIAGRAM_SHAPES.includes(input.shape) ? input.shape : 'rounded', x: Number.isFinite(input.x) ? input.x : 100, y: Number.isFinite(input.y) ? input.y : 100, width: Number.isFinite(input.width) ? input.width : 180, height: Number.isFinite(input.height) ? input.height : 72, label: input.label || 'Node', style: { fill: input.style?.fill || '#ffffff', stroke: input.style?.stroke || 'currentColor', strokeWidth: input.style?.strokeWidth || 2 } }; }
export function createConnector(input = {}) { if (!input.from || !input.to) throw new Error('Connector requires from and to node IDs'); return { id: input.id || `edge_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`, kind: 'connector', from: input.from, to: input.to, label: input.label || '', style: { strokeWidth: input.style?.strokeWidth || 2, dashed: Boolean(input.style?.dashed) } }; }
export function addDiagramNode(artifact, input) { return applyArtifactOperation(artifact, { type: OPERATION_TYPES.ADD_ELEMENT, element: createDiagramNode(input) }); }
export function updateDiagramNode(artifact, id, patch) { return applyArtifactOperation(artifact, { type: OPERATION_TYPES.UPDATE_ELEMENT, id, patch }); }
export function removeDiagramNode(artifact, id) { const next = applyArtifactOperation(artifact, { type: OPERATION_TYPES.REMOVE_ELEMENT, id }); return { ...next, content: { ...next.content, connectors: (next.content.connectors || []).filter((edge) => edge.from !== id && edge.to !== id) } }; }
export function addDiagramConnector(artifact, input) { const next = structuredClone(artifact); next.content.connectors = [...(next.content.connectors || []), createConnector(input)]; next.updatedAt = new Date().toISOString(); return next; }
export function removeDiagramConnector(artifact, id) { const next = structuredClone(artifact); next.content.connectors = (next.content.connectors || []).filter((edge) => edge.id !== id); next.updatedAt = new Date().toISOString(); return next; }
export function autoLayoutDiagram(artifact, { columns = 3, gapX = 80, gapY = 80 } = {}) { const next = structuredClone(artifact); const nodes = next.content?.elements || []; nodes.forEach((node, index) => { const column = index % columns; const row = Math.floor(index / columns); node.x = 80 + column * (node.width + gapX); node.y = 80 + row * (node.height + gapY); }); next.updatedAt = new Date().toISOString(); return next; }
function center(node) { return { x: node.x + node.width / 2, y: node.y + node.height / 2 }; }
function esc(value) { return String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char])); }
export function diagramToSvg(artifact, { standalone = true } = {}) { const content = artifact?.content || {}; const nodes = content.elements || []; const byId = new Map(nodes.map((node) => [node.id, node])); const width = content.width || 1200; const height = content.height || 800; const parts = []; if (standalone) parts.push(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="${width}" height="${height}">`); parts.push('<defs><marker id="oc-arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="currentColor"/></marker></defs>'); for (const edge of content.connectors || []) { const from = byId.get(edge.from); const to = byId.get(edge.to); if (!from || !to) continue; const a = center(from); const b = center(to); parts.push(`<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="currentColor" stroke-width="${edge.style?.strokeWidth || 2}" ${edge.style?.dashed ? 'stroke-dasharray="8 6"' : ''} marker-end="url(#oc-arrow)"/>`); if (edge.label) parts.push(`<text x="${(a.x + b.x) / 2}" y="${(a.y + b.y) / 2 - 8}" text-anchor="middle" font-size="14" fill="currentColor">${esc(edge.label)}</text>`); } for (const node of nodes) { const common = `fill="${esc(node.style?.fill || '#fff')}" stroke="${esc(node.style?.stroke || 'currentColor')}" stroke-width="${node.style?.strokeWidth || 2}"`; if (node.shape === 'ellipse') parts.push(`<ellipse cx="${node.x + node.width / 2}" cy="${node.y + node.height / 2}" rx="${node.width / 2}" ry="${node.height / 2}" ${common}/>`); else if (node.shape === 'diamond') { const cx = node.x + node.width / 2; const cy = node.y + node.height / 2; parts.push(`<polygon points="${cx},${node.y} ${node.x + node.width},${cy} ${cx},${node.y + node.height} ${node.x},${cy}" ${common}/>`); } else parts.push(`<rect x="${node.x}" y="${node.y}" width="${node.width}" height="${node.height}" rx="${node.shape === 'rounded' ? 16 : 0}" ${common}/>`); parts.push(`<text x="${node.x + node.width / 2}" y="${node.y + node.height / 2 + 5}" text-anchor="middle" font-family="system-ui,sans-serif" font-size="16" fill="currentColor">${esc(node.label)}</text>`); } if (standalone) parts.push('</svg>'); return parts.join(''); }
export function parseDiagramDsl(text) { const lines = String(text || '').split(/\r?\n/).map((line) => line.trim()).filter(Boolean); let artifact = createDiagramArtifact({ name: 'Generated diagram' }); const nodeIds = new Map(); const ensure = (label) => { if (!nodeIds.has(label)) { const node = createDiagramNode({ label, x: 100 + nodeIds.size * 220, y: 120 }); nodeIds.set(label, node.id); artifact = addDiagramNode(artifact, node); } return nodeIds.get(label); }; for (const line of lines) { const match = line.match(/^(.+?)\s*(?:->|=>)\s*(.+)$/); if (!match) { ensure(line); continue; } const from = ensure(match[1].trim()); const to = ensure(match[2].trim()); artifact = addDiagramConnector(artifact, { from, to }); } return autoLayoutDiagram(artifact); }
