/**
 * Image artifacts.
 *
 * An image generated by OpenContent used to be a loose media blob: base64 in the
 * `user-assets` store with loose metadata and no history, so it could not be
 * edited in a traceable way, undone or versioned while a PDF could.
 *
 * An image artifact closes that gap without inventing a second engine and
 * without copying a single byte:
 *
 *   - the bytes stay in `user-assets`, exactly once, in the media asset;
 *   - the artifact REFERENCES that asset through `content.mediaAssetId`;
 *   - `content.prompt`, `content.parameters` and `content.model` describe how
 *     the referenced image was produced;
 *   - changing them is a regular artifact operation (`set_image_config`), so it
 *     is undoable, redoable and versioned like any diagram or document edit.
 *
 * This module owns the shape of that content. It performs no writes and no
 * network calls: `src/services/imageArtifacts.js` orchestrates the storage side.
 */

import { ARTIFACT_TYPES, OPERATION_TYPES, createArtifact, withHistoryBase } from './artifactEngine.js';
import { getMedia } from '../mediaService.js';

/** Marks an artifact whose content follows the image contract of this module. */
const IMAGE_ARTIFACT_FORMAT = 'oc-image/1';

export const IMAGE_ERROR_CODES = Object.freeze({
    TYPE_REQUIRED: 'IMAGE_ARTIFACT_TYPE_REQUIRED',
    ASSET_REQUIRED: 'IMAGE_ASSET_REQUIRED',
    ASSET_NOT_FOUND: 'IMAGE_ASSET_NOT_FOUND',
    PROMPT_REQUIRED: 'IMAGE_PROMPT_REQUIRED',
    PARAMETERS_INVALID: 'IMAGE_PARAMETERS_INVALID',
    GENERATOR_REQUIRED: 'IMAGE_GENERATOR_REQUIRED',
    GENERATION_FAILED: 'IMAGE_GENERATION_FAILED'
});

/** Thrown by this module. Always carries a code the interface can render. */
export class ImageArtifactError extends Error {
    constructor(code, message, details = {}) {
        super(`${code}: ${message}`);
        this.name = 'ImageArtifactError';
        this.code = code;
        this.mediaAssetId = details.mediaAssetId ?? null;
    }
}

const isPlainObject = (value) => Boolean(value) && typeof value === 'object' && !Array.isArray(value);
const clone = (value) => (value == null ? value : structuredClone(value));

export function isImageArtifact(artifact) {
    return artifact?.type === ARTIFACT_TYPES.IMAGE;
}

/**
 * The generation configuration an image artifact describes.
 * Throws when the artifact is not an image artifact: reading image
 * configuration off a diagram is a bug, not an empty configuration.
 */
export function readImageConfig(artifact) {
    if (!isImageArtifact(artifact)) {
        throw new ImageArtifactError(
            IMAGE_ERROR_CODES.TYPE_REQUIRED,
            `Artifact ${artifact?.id || 'unknown'} is a ${artifact?.type || 'unknown'} artifact, not an image artifact`
        );
    }
    const content = isPlainObject(artifact.content) ? artifact.content : {};
    return {
        mediaAssetId: content.mediaAssetId || null,
        prompt: content.prompt || '',
        parameters: isPlainObject(content.parameters) ? clone(content.parameters) : {},
        model: content.model || null
    };
}

/**
 * Tolerant variant for callers that walk mixed artifact collections (the
 * Library, for one): returns null instead of throwing.
 */
export function imageMediaAssetId(artifact) {
    if (!isImageArtifact(artifact)) return null;
    const content = isPlainObject(artifact.content) ? artifact.content : null;
    return content?.mediaAssetId || null;
}

/**
 * Builds an image artifact for a media asset that already holds the bytes.
 *
 * The artifact is created from the asset, never from its `data`: passing a
 * generated image through here must not put a second copy of the bytes in the
 * `artifacts` store.
 */
export function createImageArtifact({
    asset,
    name = null,
    projectId = null,
    prompt = null,
    parameters = null,
    model = null,
    kind = null,
    source = 'generated',
    delivery = null
} = {}) {
    if (!asset?.id) {
        throw new ImageArtifactError(IMAGE_ERROR_CODES.ASSET_REQUIRED, 'An image artifact needs the media asset that holds the bytes');
    }
    return withHistoryBase(createArtifact({
        type: ARTIFACT_TYPES.IMAGE,
        name: name || asset.name || 'Untitled image',
        projectId: projectId || asset.projectId || null,
        source: source || asset.source || 'generated',
        content: {
            mediaAssetId: asset.id,
            prompt: typeof prompt === 'string' ? prompt : (asset.prompt || ''),
            parameters: isPlainObject(parameters) ? clone(parameters) : clone(isPlainObject(asset.parameters) ? asset.parameters : {}),
            model: model || asset.model || null
        },
        metadata: {
            format: IMAGE_ARTIFACT_FORMAT,
            kind: kind || asset.kind || 'generated',
            mimeType: asset.type || null
        },
        delivery: delivery || null
    }));
}

/**
 * The `set_image_config` operation that records a regeneration.
 * `validateOperation` checks the shape; this only builds it.
 */
export function setImageConfigOperation({ mediaAssetId, prompt, parameters = {}, model = null } = {}) {
    return {
        type: OPERATION_TYPES.SET_IMAGE_CONFIG,
        mediaAssetId,
        prompt,
        parameters: isPlainObject(parameters) ? clone(parameters) : {},
        model: model || null
    };
}

/**
 * Reads the media asset an image artifact points at.
 * Rejects with `IMAGE_ASSET_NOT_FOUND` when the asset is gone: an image whose
 * bytes were deleted must report that, not render as an empty artifact.
 */
export async function readImageArtifactAsset(artifact) {
    const { mediaAssetId } = readImageConfig(artifact);
    if (!mediaAssetId) {
        throw new ImageArtifactError(IMAGE_ERROR_CODES.ASSET_NOT_FOUND, 'This image artifact does not reference a media asset', { mediaAssetId: null });
    }
    const asset = await getMedia(mediaAssetId);
    if (!asset) {
        throw new ImageArtifactError(IMAGE_ERROR_CODES.ASSET_NOT_FOUND, `Media asset ${mediaAssetId} no longer exists`, { mediaAssetId });
    }
    return asset;
}