import { ARTIFACT_TYPES, OPERATION_TYPES, applyArtifactOperation, createArtifact, withHistoryBase } from './artifactEngine.js';
const PAGE_SIZES = { a4: [595.28, 841.89], letter: [612, 792] };
export function createDocumentPage(input = {}) { return { id: input.id || `page_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`, title: input.title || '', blocks: Array.isArray(input.blocks) ? structuredClone(input.blocks) : [], rotation: input.rotation || 0, width: input.width || null, height: input.height || null }; }
export function createTextBlock(input = {}) { return { id: input.id || `block_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`, type: 'text', text: input.text || '', x: input.x ?? 54, y: input.y ?? 72, width: input.width ?? 480, fontSize: input.fontSize ?? 12, lineHeight: input.lineHeight ?? 1.35, weight: input.weight || 'normal' }; }
export function createDiagramBlock(input = {}) { return { id: input.id || `block_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`, type: 'diagram', artifactId: input.artifactId || null, svg: input.svg || '', x: input.x ?? 54, y: input.y ?? 180, width: input.width ?? 480, height: input.height ?? 300 }; }
export function createDocumentArtifact({ name = 'Untitled document', projectId = null, pageSize = 'a4', prompt = null } = {}) { return withHistoryBase(createArtifact({ type: ARTIFACT_TYPES.DOCUMENT, name, projectId, prompt, content: { pageSize, pages: [createDocumentPage({ title: name })] }, metadata: { format: 'oc-document/1' } })); }
export function createPdfArtifact({ name = 'Untitled PDF', projectId = null, sourceDataUrl = null, mimeType = 'application/pdf' } = {}) { return withHistoryBase(createArtifact({ type: ARTIFACT_TYPES.PDF, name, projectId, source: sourceDataUrl ? 'upload' : 'generated', content: { originalDataUrl: sourceDataUrl, mimeType, pages: [], annotations: [] }, metadata: { format: 'oc-pdf/1', immutableOriginal: Boolean(sourceDataUrl) } })); }
export function addDocumentPage(artifact, page = createDocumentPage()) { return applyArtifactOperation(artifact, { type: OPERATION_TYPES.ADD_PAGE, page }); }
export function removeDocumentPage(artifact, pageId) { return applyArtifactOperation(artifact, { type: OPERATION_TYPES.REMOVE_PAGE, id: pageId }); }
export function reorderDocumentPages(artifact, order) { return applyArtifactOperation(artifact, { type: OPERATION_TYPES.REORDER_PAGES, order }); }
export function updateDocumentPage(artifact, pageId, patch) { return applyArtifactOperation(artifact, { type: OPERATION_TYPES.UPDATE_PAGE, id: pageId, patch }); }
export function addBlockToPage(artifactInput, pageId, block) { const artifact = structuredClone(artifactInput); artifact.content.pages = (artifact.content.pages || []).map((page) => page.id === pageId ? { ...page, blocks: [...(page.blocks || []), structuredClone(block)] } : page); artifact.updatedAt = new Date().toISOString(); return artifact; }
export function updateBlock(artifactInput, pageId, blockId, patch) { const artifact = structuredClone(artifactInput); artifact.content.pages = (artifact.content.pages || []).map((page) => page.id === pageId ? { ...page, blocks: (page.blocks || []).map((block) => block.id === blockId ? { ...block, ...structuredClone(patch) } : block) } : page); artifact.updatedAt = new Date().toISOString(); return artifact; }
export function addPdfAnnotation(artifactInput, annotation = {}) { const artifact = structuredClone(artifactInput); artifact.content.annotations = [...(artifact.content.annotations || []), { id: annotation.id || `annotation_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`, page: annotation.page || 1, type: annotation.type || 'note', text: annotation.text || '', x: annotation.x ?? 0.1, y: annotation.y ?? 0.1, width: annotation.width ?? 0.3, height: annotation.height ?? 0.08, createdAt: new Date().toISOString() }]; artifact.updatedAt = new Date().toISOString(); return artifact; }
export function removePdfAnnotation(artifactInput, annotationId) { const artifact = structuredClone(artifactInput); artifact.content.annotations = (artifact.content.annotations || []).filter((item) => item.id !== annotationId); artifact.updatedAt = new Date().toISOString(); return artifact; }
function escapePdfText(value) { return String(value || '').replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)').replace(/[^\x20-\x7E\n]/g, '?'); }
function wrapText(text, maxChars = 82) { const words = String(text || '').replace(/\s+/g, ' ').trim().split(' '); const lines = []; let current = ''; for (const word of words) { if (!word) continue; if ((current + ' ' + word).trim().length > maxChars && current) { lines.push(current); current = word; } else current = (current + ' ' + word).trim(); } if (current) lines.push(current); return lines; }
function contentStreamForPage(page, pageHeight) { const commands = ['BT', '/F1 12 Tf', '0 g']; const blocks = page.blocks || []; for (const block of blocks) { if (block.type !== 'text') continue; const size = Number(block.fontSize) || 12; const lineHeight = size * (Number(block.lineHeight) || 1.35); const x = Number(block.x) || 54; let y = pageHeight - (Number(block.y) || 72); commands.push(`/F1 ${size} Tf`); for (const line of wrapText(block.text, Math.max(20, Math.floor((Number(block.width) || 480) / (size * 0.55))))) { commands.push(`1 0 0 1 ${x.toFixed(2)} ${y.toFixed(2)} Tm (${escapePdfText(line)}) Tj`); y -= lineHeight; } } if (!blocks.length && page.title) commands.push(`1 0 0 1 54 ${(pageHeight - 72).toFixed(2)} Tm (${escapePdfText(page.title)}) Tj`); commands.push('ET'); return commands.join('\n'); }
export function serializeDocumentToPdf(documentArtifact) { const content = documentArtifact?.content || {}; const [defaultWidth, defaultHeight] = PAGE_SIZES[content.pageSize] || PAGE_SIZES.a4; const pages = content.pages?.length ? content.pages : [createDocumentPage({ title: documentArtifact?.name || 'Document' })]; const objects = []; const add = (body) => { objects.push(body); return objects.length; }; const catalogId = add(''); const pagesId = add(''); const fontId = add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'); const pageIds = []; for (const page of pages) { const width = page.width || defaultWidth; const height = page.height || defaultHeight; const stream = contentStreamForPage(page, height); const streamId = add(`<< /Length ${new TextEncoder().encode(stream).length} >>\nstream\n${stream}\nendstream`); const pageId = add(`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${width} ${height}] /Resources << /Font << /F1 ${fontId} 0 R >> >> /Contents ${streamId} 0 R /Rotate ${page.rotation || 0} >>`); pageIds.push(pageId); } objects[catalogId - 1] = `<< /Type /Catalog /Pages ${pagesId} 0 R >>`; objects[pagesId - 1] = `<< /Type /Pages /Kids [${pageIds.map((id) => `${id} 0 R`).join(' ')}] /Count ${pageIds.length} >>`; let pdf = '%PDF-1.4\n%OpenContent\n'; const offsets = [0]; for (let i = 0; i < objects.length; i += 1) { offsets.push(new TextEncoder().encode(pdf).length); pdf += `${i + 1} 0 obj\n${objects[i]}\nendobj\n`; } const xref = new TextEncoder().encode(pdf).length; pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`; for (let i = 1; i < offsets.length; i += 1) pdf += `${String(offsets[i]).padStart(10, '0')} 00000 n \n`; pdf += `trailer\n<< /Size ${objects.length + 1} /Root ${catalogId} 0 R >>\nstartxref\n${xref}\n%%EOF`; return new Blob([pdf], { type: 'application/pdf' }); }
export function downloadPdfBlob(blob, filename = 'document.pdf') { const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = filename.endsWith('.pdf') ? filename : `${filename}.pdf`; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
export function documentFromText(text, { name = 'AI document', pageSize = 'a4' } = {}) { const artifact = createDocumentArtifact({ name, pageSize }); const paragraphs = String(text || '').split(/\n{2,}/).map((part) => part.trim()).filter(Boolean); const pages = []; let current = createDocumentPage({ title: name }); let y = 72; for (const paragraph of paragraphs) { const estimatedLines = Math.max(1, Math.ceil(paragraph.length / 82)); const height = estimatedLines * 18 + 18; if (y + height > 760 && current.blocks.length) { pages.push(current); current = createDocumentPage(); y = 72; } current.blocks.push(createTextBlock({ text: paragraph, y, fontSize: pages.length === 0 && current.blocks.length === 0 ? 18 : 12 })); y += height; } pages.push(current); return { ...artifact, content: { ...artifact.content, pages } }; }
export function pdfInfo(artifact) { return { id: artifact?.id, name: artifact?.name, source: artifact?.source, generatedPages: artifact?.content?.pages?.length || 0, annotations: artifact?.content?.annotations?.length || 0, hasOriginal: Boolean(artifact?.content?.originalDataUrl), immutableOriginal: Boolean(artifact?.metadata?.immutableOriginal) }; }
